package vo;
// Generated 14/04/2015 20:30:45 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa implements java.io.Serializable {

    private int codpessoa;
    private String nome;
    private String email;
    private String telefone;
    private String celular;
    private String senha;
    private String cpf;
    private String rg;
    private Nivel nivel;
    private String imagem;
    private Date dtcadastro;
    private String bloco;
    private String apartamento;
    private String status;
    private String recebemsg;
    private String respocorrencia;
    private String fazreserva;
    private String morador;
    private String primeiroacesso;
    private String sexo;
    private Date dtnascimento;
    private int codparentesco;
    private String aceitacopiaadm;
    private String acessapainel;
    private String liberaacesso;
    private int codcategoria;
    private int codprofissao;
    private Empresa empresa;

    public Pessoa(){
    }
    
    public Pessoa(String nome){
        this.nome = nome;
    }
    
    public Pessoa(int codpessoa, int codempresa){
        this.codpessoa = codpessoa;
        this.empresa.setCodempresa(codempresa);
    }

    public int getCodpessoa() {
        return codpessoa;
    }

    public void setCodpessoa(int codpessoa) {
        this.codpessoa = codpessoa;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTelefone() {
        return telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    public String getCelular() {
        return celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    public String getRg() {
        return rg;
    }

    public void setRg(String rg) {
        this.rg = rg;
    }

    public Nivel getNivel() {
        return nivel;
    }

    public void setNivel(Nivel nivel) {
        this.nivel = nivel;
    }

    public String getImagem() {
        return imagem;
    }

    public void setImagem(String imagem) {
        this.imagem = imagem;
    }

    public Date getDtcadastro() {
        return dtcadastro;
    }

    public void setDtcadastro(Date dtcadastro) {
        this.dtcadastro = dtcadastro;
    }

    public String getBloco() {
        return bloco;
    }

    public void setBloco(String bloco) {
        this.bloco = bloco;
    }

    public String getApartamento() {
        return apartamento;
    }

    public void setApartamento(String apartamento) {
        this.apartamento = apartamento;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRecebemsg() {
        return recebemsg;
    }

    public void setRecebemsg(String recebemsg) {
        this.recebemsg = recebemsg;
    }

    public String getRespocorrencia() {
        return respocorrencia;
    }

    public void setRespocorrencia(String respocorrencia) {
        this.respocorrencia = respocorrencia;
    }

    public String getFazreserva() {
        return fazreserva;
    }

    public void setFazreserva(String fazreserva) {
        this.fazreserva = fazreserva;
    }

    public String getMorador() {
        return morador;
    }

    public void setMorador(String morador) {
        this.morador = morador;
    }

    public String getPrimeiroacesso() {
        return primeiroacesso;
    }

    public void setPrimeiroacesso(String primeiroacesso) {
        this.primeiroacesso = primeiroacesso;
    }

    public String getSexo() {
        return sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    public Date getDtnascimento() {
        return dtnascimento;
    }

    public void setDtnascimento(Date dtnascimento) {
        this.dtnascimento = dtnascimento;
    }

    public int getCodparentesco() {
        return codparentesco;
    }

    public void setCodparentesco(int codparentesco) {
        this.codparentesco = codparentesco;
    }

    public String getAceitacopiaadm() {
        return aceitacopiaadm;
    }

    public void setAceitacopiaadm(String aceitacopiaadm) {
        this.aceitacopiaadm = aceitacopiaadm;
    }

    public String getAcessapainel() {
        return acessapainel;
    }

    public void setAcessapainel(String acessapainel) {
        this.acessapainel = acessapainel;
    }

    public String getLiberaacesso() {
        return liberaacesso;
    }

    public void setLiberaacesso(String liberaacesso) {
        this.liberaacesso = liberaacesso;
    }

    public int getCodcategoria() {
        return codcategoria;
    }

    public void setCodcategoria(int codcategoria) {
        this.codcategoria = codcategoria;
    }

    public int getCodprofissao() {
        return codprofissao;
    }

    public void setCodprofissao(int codprofissao) {
        this.codprofissao = codprofissao;
    }

    public Empresa getEmpresa() {
        return empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

}
