package vo;
// Generated 14/04/2015 20:30:45 by Hibernate Tools 4.3.1



/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


    private int codproduto;
    private String nome;
    private double valor;
    private int quantidade;
    private int codempresa;
    private String codigobarra;
    private String status; 
     
     
    public Produto() {
    }

	
    public Produto(String nome, double valor, int quantidade) {
        this.nome = nome;
        this.valor = valor;
        this.quantidade = quantidade;
    }
    public Produto(String nome, double valor, int quantidade, int codempresa) {
       this.nome = nome;
       this.valor = valor;
       this.quantidade = quantidade;
       this.codempresa = codempresa;
    }
   
    public int getCodproduto() {
        return this.codproduto;
    }
    
    public void setCodproduto(int codproduto) {
        this.codproduto = codproduto;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public int getCodempresa() {
        return this.codempresa;
    }
    
    public void setCodempresa(int codempresa) {
        this.codempresa = codempresa;
    }

    /**
     * @return the codigobarra
     */
    public String getCodigobarra() {
        return codigobarra;
    }

    /**
     * @param codigobarra the codigobarra to set
     */
    public void setCodigobarra(String codigobarra) {
        this.codigobarra = codigobarra;
    }

    /**
     * @return the status
     */
    public String getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(String status) {
        this.status = status;
    }

   


}


